### ISSUE TITLE
Clojure Script date object always one day off 

### ISSUE THREAD

**Issue by inturi99** [inturi99/rrms#1]

**Comment by rajeshponnala** [comment]
from datebase itself date coming in different time zone.
converting to string giving correct date string. 
I think it is not issue of server

**Comment by tabrez** [comment]
Do we need to convert it to Date datatype? How about storing it as a string?

**Comment by tabrez** [comment]
Try this:
Use (tt/today) to get current time while inserting the document.
Use (f/unparse (f/formatter "dd/MM/yyyy") date) when displaying the date.

**Comment by rajeshponnala** [comment]
change data type of column 'date' from 'date' to 'timestamp with timezone'
